// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

///*  edited
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6nLTZ8YifrPfpDFIO34BINxtL29wxJw',
    appId: '1:114286790353:web:595c1ae682dba160d467f0',
    messagingSenderId: '114286790353',
    projectId: 'findit-2b296',
    authDomain: 'findit-2b296.firebaseapp.com',
    storageBucket: 'findit-2b296.firebasestorage.app',
    measurementId: 'G-WQS1L2QK5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV1a95V-Yc3eNvE_dnwVelhuAEQNO3OKA',
    appId: '1:114286790353:android:be58869b07a4dddbd467f0',
    messagingSenderId: '114286790353',
    projectId: 'findit-2b296',
    storageBucket: 'findit-2b296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqJFTf9Hl_GVDSINg6U7qU4rMCFzgCdg',
    appId: '1:114286790353:ios:920c3f116073584ad467f0',
    messagingSenderId: '114286790353',
    projectId: 'findit-2b296',
    storageBucket: 'findit-2b296.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPqJFTf9Hl_GVDSINg6U7qU4rMCFzgCdg',
    appId: '1:114286790353:ios:920c3f116073584ad467f0',
    messagingSenderId: '114286790353',
    projectId: 'findit-2b296',
    storageBucket: 'findit-2b296.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA6nLTZ8YifrPfpDFIO34BINxtL29wxJw',
    appId: '1:114286790353:web:1064d2f814a0f687d467f0',
    messagingSenderId: '114286790353',
    projectId: 'findit-2b296',
    authDomain: 'findit-2b296.firebaseapp.com',
    storageBucket: 'findit-2b296.firebasestorage.app',
    measurementId: 'G-76DNR1XRDN',
  );
}
